[package]
name = "_fast"
version = "0.1.0"
edition = "2021"

[lib]
name = "_fast"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
regex = "1"
rayon = "1.7"   # for parallel processing
