[package]
name = "_fast"
version = "0.1.0"
edition = "2021"

[lib]
name = "_fast"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
lazy_static = "1.4"
rayon = "1.11"
regex = "1.10"

[dev-dependencies]
criterion = "0.7.0"
